name: Docker Build und Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Manuelle Ausführung ermöglichen
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner | lower }}/${{ github.event.repository.name | lower }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Für Tag-Erstellung
      packages: write    # Für ghcr.io Push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build und Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extrahiere Tag-Namen
        id: tag
        if: github.event_name != 'pull_request'
        run: echo "TAG_NAME=$(echo '${{ steps.meta.outputs.tags }}' | head -n 1 | sed 's/.*://')" >> $GITHUB_OUTPUT

      - name: Erstelle Git-Tag
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ steps.tag.outputs.TAG_NAME }}" -m "Release v${{ steps.tag.outputs.TAG_NAME }}"
          git push origin "v${{ steps.tag.outputs.TAG_NAME }}"
